### ISSUE TITLE
Replace auth package with casdoor-go-sdk

### ISSUE THREAD

**Issue by bnuluohf** [open-ct/openscore#7]
Replace: https://github.com/open-ct/openscore/tree/master/auth with: https://github.com/casdoor/casdoor-go-sdk

**Comment by bnuluohf** [comment]
@TAODEI

**Comment by TAODEI** [comment]
have done

**Comment by bnuluohf** [comment]
@TAODEI see my comment here: https://github.com/open-ct/openscore/pull/8#issuecomment-1196657421

This issue also has been resolved at: https://github.com/open-ct/openscore/commit/fff44a57433b27f70db8f856a79cdfda2ffebffd
